matrix:
    include:
        - os: linux
          dist: xenial
          language: python
          python: 3.7
        - os: osx
          language: generic
          env: PYTHON=3.7.3
before_install:
    - .travis/install.sh
    - source .travis/activate_virtualenv.sh
install:
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - pytest --gmake=make -n 4 . --cov=.
env:
    - CODECOV_TOKEN=50b5404b-09c4-4915-b59f-01c0948b857d
after_success:
    - codecov
